// SPDX-License-Identifier: AGPL-3.0-or-later
import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Auto-Fix & AI Author Mode — DocuGardener Docs",
  description:
    "Automatically generate and merge documentation fixes for AI-authored pull requests.",
}

export default function AutoFixPage() {
  return (
    <>
      <h1 className="text-3xl font-extrabold text-gray-900 tracking-tight mb-2">
        Auto-Fix &amp; AI Author Mode
      </h1>
      <p className="text-lg text-gray-500 mb-8">
        Let DocuGardener handle documentation updates automatically — especially for
        AI-authored code.
      </p>

      {/* ── Auto-Fix ─────────────────────────────────────── */}
      <h2 className="text-xl font-bold text-gray-900 mt-10 mb-3">Auto-Fix</h2>
      <p className="text-gray-600 leading-relaxed mb-4">
        When DocuGardener detects documentation drift, it generates exact Markdown diffs showing
        what needs to change. You can apply these fixes in two ways:
      </p>
      <ul className="list-disc list-inside text-gray-600 space-y-2 mb-4">
        <li>
          <strong>One-click from the Triage Inbox</strong> — Click &ldquo;Apply fix&rdquo; on any
          finding. DocuGardener opens a pull request with the suggested documentation changes,
          linked back to the original analysis.
        </li>
        <li>
          <strong>Automatic via AI Author Mode</strong> — When enabled, DocuGardener creates and
          merges fix PRs without any human intervention for qualifying pull requests (see below).
        </li>
      </ul>

      {/* ── AI Author Mode ───────────────────────────────── */}
      <h2 className="text-xl font-bold text-gray-900 mt-10 mb-3">AI Author Mode</h2>
      <p className="text-gray-600 leading-relaxed mb-4">
        AI Author Mode is designed for teams that use AI coding agents extensively. When a pull
        request is authored by an AI tool — and documentation drift is detected — DocuGardener
        automatically opens a fix PR and merges it once CI passes. Zero human intervention.
      </p>

      <h3 className="text-base font-bold text-gray-800 mt-6 mb-2">
        How DocuGardener Detects AI-Authored PRs
      </h3>
      <p className="text-gray-600 leading-relaxed mb-4">
        DocuGardener uses four signals to determine whether a PR was authored by an AI agent:
      </p>
      <table className="w-full text-sm border-collapse mb-6">
        <thead>
          <tr>
            <th className="text-left bg-gray-50 px-3 py-2 border border-gray-200 font-semibold text-gray-700">
              Signal
            </th>
            <th className="text-left bg-gray-50 px-3 py-2 border border-gray-200 font-semibold text-gray-700">
              Example
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td className="px-3 py-2 border border-gray-200 text-gray-600 font-medium">
              Bot sender
            </td>
            <td className="px-3 py-2 border border-gray-200 text-gray-600">
              PR opened by{" "}
              <code className="bg-gray-100 text-gray-800 px-1.5 py-0.5 rounded text-sm font-mono">
                dependabot[bot]
              </code>
              ,{" "}
              <code className="bg-gray-100 text-gray-800 px-1.5 py-0.5 rounded text-sm font-mono">
                renovate[bot]
              </code>
              , or a GitHub App
            </td>
          </tr>
          <tr>
            <td className="px-3 py-2 border border-gray-200 text-gray-600 font-medium">
              Branch prefix
            </td>
            <td className="px-3 py-2 border border-gray-200 text-gray-600">
              Branch starts with{" "}
              <code className="bg-gray-100 text-gray-800 px-1.5 py-0.5 rounded text-sm font-mono">
                copilot/
              </code>
              ,{" "}
              <code className="bg-gray-100 text-gray-800 px-1.5 py-0.5 rounded text-sm font-mono">
                cursor/
              </code>
              ,{" "}
              <code className="bg-gray-100 text-gray-800 px-1.5 py-0.5 rounded text-sm font-mono">
                devin/
              </code>
              , or{" "}
              <code className="bg-gray-100 text-gray-800 px-1.5 py-0.5 rounded text-sm font-mono">
                claude/
              </code>
            </td>
          </tr>
          <tr>
            <td className="px-3 py-2 border border-gray-200 text-gray-600 font-medium">
              PR body marker
            </td>
            <td className="px-3 py-2 border border-gray-200 text-gray-600">
              PR description contains known AI tool signatures (e.g. &ldquo;Generated by
              Copilot&rdquo;)
            </td>
          </tr>
          <tr>
            <td className="px-3 py-2 border border-gray-200 text-gray-600 font-medium">
              Custom pattern
            </td>
            <td className="px-3 py-2 border border-gray-200 text-gray-600">
              A regex pattern you define in Agent Governance settings
            </td>
          </tr>
        </tbody>
      </table>
      <p className="text-gray-600 leading-relaxed mb-4">
        If <strong>any</strong> of these signals match, the PR is classified as AI-authored.
      </p>

      {/* ── When it fires ────────────────────────────────── */}
      <h3 className="text-base font-bold text-gray-800 mt-6 mb-2">
        When Does AI Author Mode Fire?
      </h3>
      <p className="text-gray-600 leading-relaxed mb-4">
        AI Author Mode fires when all three conditions are met:
      </p>
      <ol className="list-decimal list-inside text-gray-600 space-y-2 mb-4">
        <li>The PR is detected as AI-authored (any of the four signals above).</li>
        <li>AI Author Mode is enabled in your settings.</li>
        <li>
          The drift analysis found at least one documentation update to make (i.e. the suggested
          fix is non-empty).
        </li>
      </ol>
      <p className="text-gray-600 leading-relaxed mb-4">
        When these conditions are met, DocuGardener opens a documentation fix PR targeting the same
        base branch and attempts to auto-merge it after CI passes.
      </p>

      {/* ── Auto-merge methods ───────────────────────────── */}
      <h3 className="text-base font-bold text-gray-800 mt-6 mb-2">Auto-Merge Methods</h3>
      <p className="text-gray-600 leading-relaxed mb-4">
        You can configure which merge strategy DocuGardener uses for auto-merging fix PRs:
      </p>
      <ul className="list-disc list-inside text-gray-600 space-y-2 mb-4">
        <li>
          <strong>Squash</strong> (default) — All fix commits are squashed into a single commit.
        </li>
        <li>
          <strong>Merge commit</strong> — A standard merge commit is created.
        </li>
        <li>
          <strong>Rebase</strong> — Fix commits are rebased onto the target branch.
        </li>
      </ul>

      {/* ── CI gate ──────────────────────────────────────── */}
      <h2 className="text-xl font-bold text-gray-900 mt-10 mb-3">CI Gate</h2>
      <div className="bg-amber-50 border border-amber-100 rounded-lg p-4 text-sm text-amber-800 mb-4">
        <strong>Safety first:</strong> Auto-merge is skipped if any required CI check fails on the
        fix PR. In that case, the fix PR stays open for manual review.
      </div>
      <p className="text-gray-600 leading-relaxed mb-4">
        DocuGardener polls the fix PR&rsquo;s check status using exponential backoff. Once all
        required checks pass, the PR is merged automatically. If checks fail, the finding in the
        Triage Inbox transitions from &ldquo;AI working&rdquo; to &ldquo;Fix ready&rdquo; with a
        note that manual review is needed.
      </p>

      {/* ── Auto-Heal (drift score) ──────────────────────── */}
      <h2 className="text-xl font-bold text-gray-900 mt-10 mb-3">Auto-Heal Mode</h2>
      <p className="text-gray-600 leading-relaxed mb-4">
        In addition to AI Author Mode, DocuGardener supports <strong>Auto-Heal</strong> — which
        triggers a fix PR for <em>any</em> pull request (not just AI-authored ones) when the drift
        score meets or exceeds a configurable threshold. Enable this in{" "}
        <strong>Settings &rarr; Agent Governance &rarr; Auto-Heal</strong>.
      </p>

      {/* ── Configuration ────────────────────────────────── */}
      <h2 className="text-xl font-bold text-gray-900 mt-10 mb-3">Configuration</h2>
      <p className="text-gray-600 leading-relaxed mb-4">
        Both AI Author Mode and Auto-Heal are configured in{" "}
        <strong>Settings &rarr; Agent Governance</strong>:
      </p>
      <ul className="list-disc list-inside text-gray-600 space-y-2 mb-4">
        <li>
          <strong>AI Author Mode toggle</strong> — Enable or disable automatic fix PRs for
          AI-authored PRs.
        </li>
        <li>
          <strong>Auto-merge method</strong> — Choose squash, merge, or rebase.
        </li>
        <li>
          <strong>Auto-Heal toggle</strong> — Enable automatic fix PRs for all PRs above the drift
          threshold.
        </li>
        <li>
          <strong>Auto-Heal threshold</strong> — Drift score at which Auto-Heal fires (default
          matches your{" "}
          <code className="bg-gray-100 text-gray-800 px-1.5 py-0.5 rounded text-sm font-mono">
            DRIFT_SCORE_THRESHOLD
          </code>
          ).
        </li>
      </ul>
    </>
  )
}
