from pathlib import Path
import re
import time
from github import Github, GithubException
from src.core.logging import get_logger
from src.pipeline.analyzer import PRAnalysisResult
import git
import shutil
import uuid

logger = get_logger(__name__)

class GitCommitter:
    """
    Handles git operations to commit changes and create PRs.
    """
    
    def __init__(self, installation_token: str, owner: str, repo: str):
        self.token = installation_token
        self.owner = owner
        self.repo = repo
        self.repo_url = f"https://x-access-token:{installation_token}@github.com/{owner}/{repo}.git"

    def _sanitize_branch_name(self, name: str) -> str:
        """Sanitizes strings for use as git branch names."""
        import re
        # Replace non-alphanumeric with dash
        sanitized = re.sub(r'[^a-zA-Z0-9\-_]', '-', name)
        # Remove consecutive dashes
        sanitized = re.sub(r'-+', '-', sanitized)
        return sanitized.strip('-')

    def apply_and_push(self, result: PRAnalysisResult, original_head_sha: str) -> str | None:
        """
        Applies changes to a new branch and pushes to remote.
        Returns the branch name if successful, or None.
        """
        if not result.documentation_updates:
            logger.info("No updates to commit")
            return None
            
        uuid_short = uuid.uuid4().hex[:6]
        branch_name = self._sanitize_branch_name(f"docugardener/fix-{result.pr_number}-{uuid_short}")
        
        # We use a unique temp dir to avoid collisions
        tmp_dir = Path(f"/tmp/docugardener-fix-{result.pr_number}-{uuid_short}")
        if tmp_dir.exists():
            shutil.rmtree(tmp_dir)
            
        try:
            logger.info("Cloning for fix", repo=self.repo, branch=branch_name)
            
            # Clone all branches shallowly so the PR HEAD SHA is reachable
            # (depth=1 per branch tip; without no_single_branch only the default
            # branch is cloned and the PR HEAD SHA would be unreachable)
            repo = git.Repo.clone_from(self.repo_url, tmp_dir, depth=50, no_single_branch=True)

            # Create and checkout new branch from the specific SHA.
            # Shallow clones may not contain the tree objects for older/deleted-branch SHAs
            # (git reports "fatal: unable to read tree").  Fetch the exact commit first as a
            # fallback so that accepted-changes on older PRs still succeed.
            try:
                repo.git.checkout(original_head_sha)
            except git.GitCommandError:
                logger.info(
                    "SHA not in shallow clone — fetching it directly",
                    sha=original_head_sha,
                    repo=self.repo,
                )
                repo.git.fetch("origin", original_head_sha, depth=1)
                repo.git.checkout(original_head_sha)
            repo.git.checkout("-b", branch_name)
            
            # Apply changes
            files_changed = 0
            for update in result.documentation_updates:
                file_path = tmp_dir / update.file_path
                file_path.parent.mkdir(parents=True, exist_ok=True)
                
                with open(file_path, "w", encoding="utf-8") as f:
                    f.write(update.content)
                
                repo.index.add([str(update.file_path)])
                files_changed += 1
                
            if files_changed == 0:
                logger.warning("No files were changed during apply")
                return None
                
            # Commit with clear message
            commit_msg = (
                f"docs: update documentation for PR #{result.pr_number}\n\n"
                f"This commit was automatically generated by DocuGardener 🌱\n"
                f"to resolve documentation drift detected in PR #{result.pr_number}."
            )
            repo.index.commit(commit_msg)
            
            # Push
            origin = repo.remote(name="origin")
            origin.push(branch_name)
            
            logger.info("Pushed fix branch", branch=branch_name)
            return branch_name
            
        except Exception as e:
            logger.error("Failed to push fix branch", error=str(e), repo=self.repo)
            return None # Return None to trigger fail_job in handler
        finally:
            if tmp_dir.exists():
                try:
                    shutil.rmtree(tmp_dir)
                except Exception as e:
                    logger.warning("Failed to cleanup temp dir", path=str(tmp_dir), error=str(e))

    def post_pr_comment(self, pr_number: int, body: str) -> None:
        """Post a comment on a Pull Request."""
        try:
            g = Github(self.token)  # noqa: module-level import
            repo = g.get_repo(f"{self.owner}/{self.repo}")
            pr = repo.get_pull(pr_number)
            pr.create_issue_comment(body)
            logger.info("Posted PR comment", pr=pr_number)
        except Exception as e:
            logger.warning("Failed to post PR comment", pr=pr_number, error=str(e))

    def auto_merge_pr(
        self,
        pr_url: str,
        method: str = "squash",
        wait_for_ci: bool = True,
        max_retries: int = 10,
        retry_delay: int = 10,
        max_delay: int = 60,
    ) -> str | None:
        """
        Merge a PR automatically, optionally waiting for CI checks to pass.

        Args:
            pr_url: GitHub PR HTML URL (used to extract PR number).
            method: Merge method — "squash", "merge", or "rebase".
            wait_for_ci: If True, poll combined status until it passes.
            max_retries: Maximum polling attempts before giving up.
            retry_delay: Seconds between polling attempts.

        Returns:
            None if the PR was merged successfully.
            A skip-reason string otherwise: "method_not_allowed", "ci_failed",
            "ci_timeout", or "error".
        """
        match = re.search(r"/pull/(\d+)", pr_url)
        if not match:
            logger.error("auto_merge_pr: could not parse PR number from URL", pr_url=pr_url)
            return "error"

        pr_number = int(match.group(1))

        try:
            g = Github(self.token)
            repo = g.get_repo(f"{self.owner}/{self.repo}")
            pr = repo.get_pull(pr_number)

            # MOAT-01: pre-validate that the repo allows the configured merge method.
            # Catches mis-configuration early — before spending time waiting for CI —
            # and surfaces a clear error instead of a cryptic 405 from the GitHub API.
            _method_flag_map = {
                "squash": "allow_squash_merge",
                "merge": "allow_merge_commit",
                "rebase": "allow_rebase_merge",
            }
            _flag = _method_flag_map.get(method)
            if _flag and not getattr(repo, _flag, True):
                logger.error(
                    "auto_merge_pr: merge method not allowed by repository settings",
                    pr=pr_number,
                    method=method,
                )
                return "method_not_allowed"

            if wait_for_ci:
                # Use Check Runs API (covers GitHub Actions) rather than Commit Status API
                # (which only covers legacy status checks and always returns total_count=0
                # for Actions-only repos). Filter out DocuGardener's own check run.
                for attempt in range(max_retries):
                    commit = repo.get_commit(pr.head.sha)
                    check_runs = list(commit.get_check_runs())
                    external = [c for c in check_runs if c.app.slug != "docugardener"]

                    if not external:
                        if attempt == 0:
                            # First poll: Actions may not have queued yet — wait one interval
                            logger.info(
                                "auto_merge_pr: no check runs yet, waiting for CI to queue",
                                pr=pr_number,
                                attempt=attempt + 1,
                                max_retries=max_retries,
                            )
                            time.sleep(min(retry_delay * (2 ** attempt), max_delay))
                            continue
                        # Still no checks after waiting — repo has no CI configured
                        break

                    failed = [c for c in external if c.status == "completed" and c.conclusion in ("failure", "cancelled", "timed_out", "action_required")]
                    if failed:
                        logger.error(
                            "auto_merge_pr: CI failed — skipping merge",
                            pr=pr_number,
                            failed_checks=[c.name for c in failed],
                        )
                        return "ci_failed"

                    passed = all(
                        c.status == "completed" and c.conclusion in ("success", "neutral", "skipped")
                        for c in external
                    )
                    if passed:
                        break

                    if attempt < max_retries - 1:
                        logger.info(
                            "auto_merge_pr: CI pending, retrying",
                            pr=pr_number,
                            attempt=attempt + 1,
                            max_retries=max_retries,
                            pending_checks=[c.name for c in external if c.status != "completed"],
                        )
                        time.sleep(min(retry_delay * (2 ** attempt), max_delay))
                else:
                    logger.error(
                        "auto_merge_pr: CI polling timed out",
                        pr=pr_number,
                        max_retries=max_retries,
                    )
                    return "ci_timeout"

            # GitHub returns 405 "Merge already in progress" when its backend is still
            # processing a concurrent merge.  Retry up to 3 times with a short delay.
            _merge_retries = 3
            for _attempt in range(_merge_retries):
                try:
                    pr.merge(merge_method=method)
                    logger.info("auto_merge_pr: PR merged successfully", pr=pr_number, method=method)
                    return None
                except GithubException as _me:
                    if _me.status == 405 and "already in progress" in str(_me).lower() and _attempt < _merge_retries - 1:
                        logger.warning(
                            "auto_merge_pr: merge already in progress, retrying",
                            pr=pr_number,
                            attempt=_attempt + 1,
                        )
                        time.sleep(5)
                        continue
                    raise  # re-raise for the outer handler

        except GithubException as e:
            logger.error("auto_merge_pr: merge failed", pr=pr_number, error=str(e))
            return "error"

    def find_open_fix_pr(self, original_pr_number: int) -> str | None:
        """Return the HTML URL of an existing open fix PR for the given original PR number.

        Searches open PRs whose head branch matches the docugardener-fix-{pr_number}-* pattern.
        Returns None if no such PR exists.
        """
        try:
            g = Github(self.token)
            repo = g.get_repo(f"{self.owner}/{self.repo}")
            prefix = f"docugardener-fix-{original_pr_number}-"
            for pr in repo.get_pulls(state="open"):
                if pr.head.ref.startswith(prefix):
                    logger.info(
                        "find_open_fix_pr: found existing fix PR",
                        pr_number=pr.number,
                        branch=pr.head.ref,
                    )
                    return pr.html_url
        except Exception as e:
            logger.warning("find_open_fix_pr: error searching PRs", error=str(e))
        return None

    def create_pr(
        self,
        branch_name: str,
        original_pr_number: int,
        base_ref: str,
        confidence_score: float | None = None,
        recheck_status: str | None = None,
        ai_signal: str | None = None,
    ) -> str:
        """Creates a PR for the fix branch."""
        g = Github(self.token)
        repo = g.get_repo(f"{self.owner}/{self.repo}")

        title = f"docs: fix documentation drift from #{original_pr_number}"

        # FIX-01: include confidence and recheck metadata in the PR body
        _conf_pct = f"{round(confidence_score * 100)}%" if confidence_score is not None else "—"
        _recheck_icon = {"passed": "✅ Passed", "failed": "⚠️ Failed", "skipped": "⏭ Skipped"}.get(
            recheck_status or "", "—"
        )
        # MOAT-02: surface the AI authorship detection signal so reviewers know WHY
        # this fix PR was opened automatically rather than queued to the inbox.
        _ai_signal_labels = {
            "bot_suffix": "Bot sender (GitHub Actions / Copilot Workspace)",
            "branch_prefix": "Branch prefix (e.g. `copilot/`, `cursor/`, `claude/`)",
            "body_marker": "Attribution marker in PR body",
            "custom_pattern": "Tenant custom AI author pattern",
        }
        _ai_row = (
            f"| AI Authorship Signal | {_ai_signal_labels.get(ai_signal, ai_signal)} |\n"
            if ai_signal else ""
        )
        body = (
            f"## 🌱 DocuGardener Documentation Fix\n\n"
            f"This PR was automatically generated to align documentation with the changes in #{original_pr_number}.\n\n"
            f"### Summary of Changes\n"
            f"The documentation has been updated based on the semantic analysis of the code drift. "
            f"Please review these changes and merge them to resolve the drift alert.\n\n"
            f"### Analysis Metadata\n"
            f"| Field | Value |\n"
            f"|---|---|\n"
            f"| Drift Analysis Confidence | {_conf_pct} |\n"
            f"| Documentation Recheck | {_recheck_icon} |\n"
            f"{_ai_row}"
            f"\n---\n"
            f"*Generated by [DocuGardener](https://github.com/apps/docugardener)*"
        )
        
        try:
            pr = repo.create_pull(
                title=title,
                body=body,
                head=branch_name,
                base=base_ref
            )
            logger.info("Created Fix PR", url=pr.html_url)
            return pr.html_url
        except Exception as e:
            logger.error("Failed to create GitHub PR", error=str(e))
            raise e
