"use client"

import { useState } from "react"
import { toast } from "sonner"
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

const DEFAULT_TEMPLATE = `## 📝 Documentation Drift Detected
**Drift Score**: {{drift_score}}/100

DocuGardener has analyzed this PR and found changes that require documentation updates.

### Required Updates
{{files_list}}

<br/>

---
*Generated by [DocuGardener](https://github.com/docugardener)*`

export function NotificationConfigForm({ initialTemplate }: { initialTemplate?: string }) {
    const [currentInitial, setCurrentInitial] = useState(initialTemplate || DEFAULT_TEMPLATE)
    const [template, setTemplate] = useState(currentInitial)
    const [loading, setLoading] = useState(false)

    const isDirty = template !== currentInitial

    const handleSave = async () => {
        setLoading(true)
        try {
            await fetch("/api/settings", {
                method: "POST",
                body: JSON.stringify({
                    notificationTemplate: template
                })
            })
            setCurrentInitial(template)
            toast.success("Template saved!")
        } catch (error) {
            console.error(error)
            alert("Failed to save template")
        } finally {
            setLoading(false)
        }
    }

    const handleReset = () => {
        setTemplate(currentInitial)
        toast.info("Changes discarded")
    }

    const handleRestoreDefault = () => {
        setTemplate(DEFAULT_TEMPLATE)
    }

    return (
        <div className="space-y-6">
            <div className="space-y-2">
                <Label>PR Comment Template</Label>
                <Textarea
                    className="font-mono text-xs min-h-[250px]"
                    value={template}
                    onChange={(e) => setTemplate(e.target.value)}
                />
                <p className="text-[11px] text-muted-foreground mt-2 flex items-center gap-2">
                    <span className="font-bold text-primary">PRO TIP:</span> Available variables: <code>{'{{drift_score}}'}</code>, <code>{'{{summary}}'}</code>, <code>{'{{files_list}}'}</code>
                </p>
            </div>

            <div className="flex flex-col md:flex-row justify-between items-center gap-4 pt-6 border-t border-border mt-6">
                <Button variant="outline" onClick={handleRestoreDefault} size="sm" className="text-[10px] uppercase font-bold tracking-widest text-muted-foreground border-border">
                    Restore Engine Default
                </Button>
                <div className="flex gap-3 w-full md:w-auto">
                    <Button
                        type="button"
                        variant="ghost"
                        onClick={handleReset}
                        disabled={!isDirty || loading}
                        className="text-muted-foreground hover:text-foreground hover:bg-muted flex-1 md:flex-none"
                    >
                        Reset
                    </Button>
                    <Button
                        onClick={handleSave}
                        disabled={!isDirty || loading}
                        className="btn-premium bg-primary hover:bg-primary/90 text-primary-foreground min-w-[120px] flex-1 md:flex-none font-bold uppercase tracking-widest text-[10px]"
                    >
                        {loading ? "Saving..." : "Save Template"}
                    </Button>
                </div>
            </div>
        </div>
    )
}
