{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "docugardener.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "docugardener.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "docugardener.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "docugardener.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
